extends: airbnb
plugins:
  - jsx-a11y
  - import
  - react
rules:
  react/prefer-stateless-function: off
  react/sort-comp: warn
  react/jsx-filename-extension: off
  linebreak-style: off
  no-undef: error
